# 시작하기
## Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
# 초기화 되지 않은 5x3 행렬 생성
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# 무작위로 초기화된 5x3 행렬 생성
x = torch.rand(5, 3)
print(x)

tensor([[0.7779, 0.7291, 0.7002],
        [0.6604, 0.1201, 0.3061],
        [0.4628, 0.7032, 0.4128],
        [0.3210, 0.2779, 0.7583],
        [0.0754, 0.5646, 0.4065]])


In [4]:
# 행렬의 크기 구하기
print(x.size())

torch.Size([5, 3])


## Operations

### 1. 덧셈

In [5]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.5370, 1.1625, 0.9605],
        [1.4953, 0.5903, 0.7169],
        [0.5950, 1.1311, 1.0655],
        [0.5884, 0.4654, 0.9608],
        [0.6232, 1.1742, 0.9841]])


In [6]:
print(torch.add(x, y))

tensor([[1.5370, 1.1625, 0.9605],
        [1.4953, 0.5903, 0.7169],
        [0.5950, 1.1311, 1.0655],
        [0.5884, 0.4654, 0.9608],
        [0.6232, 1.1742, 0.9841]])


In [ ]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)

In [8]:
y.add_(x)
print(y)

tensor([[1.5370, 1.1625, 0.9605],
        [1.4953, 0.5903, 0.7169],
        [0.5950, 1.1311, 1.0655],
        [0.5884, 0.4654, 0.9608],
        [0.6232, 1.1742, 0.9841]])


In [10]:
# numpy 스타일의 인덱싱 사용
print(x)
print(x[:, 1]) # 두번째 열을 출력

tensor([[0.7779, 0.7291, 0.7002],
        [0.6604, 0.1201, 0.3061],
        [0.4628, 0.7032, 0.4128],
        [0.3210, 0.2779, 0.7583],
        [0.0754, 0.5646, 0.4065]])
tensor([0.7291, 0.1201, 0.7032, 0.2779, 0.5646])


In [11]:
# 크기 변경: tensor의 크기를 변경하거나 모양을 바꾸고 싶을 때, torch.view를 사용  
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1은 다른 차원에서 유추
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
print(y)
print(z)

tensor([ 2.8613, -0.7440,  0.6890,  1.1402,  1.2024, -0.4290, -1.1916,  2.0766,
         0.7143,  0.4224,  1.4410,  1.1145,  0.9819, -1.0350,  1.7331, -0.3794])
tensor([[ 2.8613, -0.7440,  0.6890,  1.1402,  1.2024, -0.4290, -1.1916,  2.0766],
        [ 0.7143,  0.4224,  1.4410,  1.1145,  0.9819, -1.0350,  1.7331, -0.3794]])


## Numpy 변환(Bridge)

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Numpy 배열을 Torch Tensor로 변환하기

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Cuda Tensors

In [20]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y